// <auto-generated />
using System;
using FancyFrenchStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FancyFrenchStore.Migrations
{
    [DbContext(typeof(FancyFrenchStoreContext))]
    [Migration("20240402002550_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FancyFrenchStore.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FancyFrenchStore.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 621, DateTimeKind.Local).AddTicks(3727),
                            Description = "Great Taste is a family tradition.",
                            LogoURL = "https://www.furmanos.com/sites/all/themes/bootstrap/furmanos/logo.png",
                            Name = "Furmano's",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 621, DateTimeKind.Local).AddTicks(3746),
                            Website = "https://www.furmanos.com/"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 621, DateTimeKind.Local).AddTicks(3840),
                            Description = "Infinite possibilities.  One Family.",
                            LogoURL = "https://www.richsusa.com/wp-content/uploads/2020/02/logo.png",
                            Name = "Rich's",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 621, DateTimeKind.Local).AddTicks(3842),
                            Website = "https://www.richsusa.com/business-solutions/foodservice/"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 621, DateTimeKind.Local).AddTicks(3865),
                            Description = "Together We Make Food Extraordinary",
                            LogoURL = "https://www.venturafoods.ca/wp-content/uploads/sites/2/2023/04/ventura_foods_CANADA_logo_white-2.png",
                            Name = "Ventura Foods Products",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 621, DateTimeKind.Local).AddTicks(3867),
                            Website = "https://www.venturafoods.ca/"
                        });
                });

            modelBuilder.Entity("FancyFrenchStore.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrimaryAddressID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FancyFrenchStore.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FancyFrenchStore.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FancyFrenchStore.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaymentAddressID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PaymentTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FancyFrenchStore.PaymentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("FancyFrenchStore.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BrandID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Discontinued")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProdPkgHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProdPkgLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProdPkgWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProdPkgWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7087157-4ecb-4898-850b-b8e3a2757980"),
                            BrandID = 1,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(7932),
                            Description = "Furmano's #10 Can Tomato Sauce",
                            Discontinued = false,
                            Model = "F12265",
                            Name = "#10 Can Tomato Sauce",
                            Price = 5.49m,
                            ProdPkgHeight = 8m,
                            ProdPkgLength = 6m,
                            ProdPkgWeight = 8m,
                            ProdPkgWidth = 6m,
                            SKU = "10610463",
                            UPC = "411880416384",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(7974)
                        },
                        new
                        {
                            Id = new Guid("108b250a-4eb7-4447-8c10-47e47efa138d"),
                            BrandID = 1,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8199),
                            Description = "Furmano's #10 Can Tomato Sauce - 6/Case",
                            Discontinued = false,
                            Model = "F12265",
                            Name = "#10 Can Tomato Sauce - 6/Case",
                            Price = 29.99m,
                            ProdPkgHeight = 8m,
                            ProdPkgLength = 19m,
                            ProdPkgWeight = 45m,
                            ProdPkgWidth = 13m,
                            SKU = "10610464",
                            UPC = "411880416384",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8201)
                        },
                        new
                        {
                            Id = new Guid("9b80187b-ae56-415e-8d86-a4fcb4de2c09"),
                            BrandID = 1,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8270),
                            Description = "Furmano's #10 Can Home Style Spaghetti Sauce",
                            Discontinued = false,
                            Model = "F10377",
                            Name = "#10 Can Home Style Spaghetti Sauce",
                            Price = 5.19m,
                            ProdPkgHeight = 8m,
                            ProdPkgLength = 6m,
                            ProdPkgWeight = 8m,
                            ProdPkgWidth = 6m,
                            SKU = "99910377",
                            UPC = "41188109338",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8272)
                        },
                        new
                        {
                            Id = new Guid("04772cb6-5c29-4f45-a6fd-3c835bb96207"),
                            BrandID = 1,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8322),
                            Description = "Furmano's #10 Can Home Style Spaghetti Sauce - 6/Case",
                            Discontinued = false,
                            Model = "F10377",
                            Name = "#10 Can Home Style Spaghetti Sauce - 6/Case",
                            Price = 27.99m,
                            ProdPkgHeight = 8m,
                            ProdPkgLength = 19m,
                            ProdPkgWeight = 45m,
                            ProdPkgWidth = 13m,
                            SKU = "99910378",
                            UPC = "41188109338",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8324)
                        },
                        new
                        {
                            Id = new Guid("4c177d0c-a8d7-433c-bd6a-487a029a80da"),
                            BrandID = 2,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8363),
                            Description = "Rich's 12 inch Fresh N Ready Freezer-to-Oven Sheeted Pizza Crust Dough - 24/Case",
                            Discontinued = false,
                            Model = "876RICH07366",
                            Name = "12 inch Sheeted Pizza Crust Dough - 24/Case",
                            Price = 67.99m,
                            ProdPkgHeight = 13m,
                            ProdPkgLength = 25m,
                            ProdPkgWeight = 14m,
                            ProdPkgWidth = 13m,
                            SKU = "876RICH07366",
                            UPC = "49800073661",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8365)
                        },
                        new
                        {
                            Id = new Guid("ec523528-3b8d-4d95-be94-cc2f77ed04c9"),
                            BrandID = 2,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8406),
                            Description = "Rich's 16 inch Fresh N Ready Freezer-to-Oven Sheeted Pizza Crust Dough - 20/Case",
                            Discontinued = false,
                            Model = "876RICH03604",
                            Name = "16 inch Sheeted Pizza Crust Dough - 20/Case",
                            Price = 94.49m,
                            ProdPkgHeight = 11m,
                            ProdPkgLength = 33m,
                            ProdPkgWeight = 20m,
                            ProdPkgWidth = 17m,
                            SKU = "876RICH03604",
                            UPC = "400013729873",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8408)
                        },
                        new
                        {
                            Id = new Guid("26d04719-aca9-4a7f-b69b-ec47534d6972"),
                            BrandID = 2,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8445),
                            Description = "Rich's 7 inch Fresh N Ready Freezer-to-Oven Sheeted Pizza Crust Dough - 72/Case",
                            Discontinued = false,
                            Model = "876RICH07386",
                            Name = "7 inch Sheeted Pizza Crust Dough - 72/Case",
                            Price = 86.99m,
                            ProdPkgHeight = 13m,
                            ProdPkgLength = 22m,
                            ProdPkgWeight = 16m,
                            ProdPkgWidth = 15m,
                            SKU = "876RICH07386",
                            UPC = "49800073869",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8446)
                        },
                        new
                        {
                            Id = new Guid("42ca0d01-facf-476e-b418-fd3e6b5bf125"),
                            BrandID = 3,
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8483),
                            Description = "Grandioso by Ventura Foods 1.5 oz. Garlic Sauce Dipping Cup - 96/Case",
                            Discontinued = false,
                            Model = "125VF480GND",
                            Name = "1.5 oz. Garlic Sauce Dipping Cup - 96/Case",
                            Price = 49.99m,
                            ProdPkgHeight = 6m,
                            ProdPkgLength = 12m,
                            ProdPkgWeight = 8m,
                            ProdPkgWidth = 8m,
                            SKU = "125VF480GND",
                            UPC = "10026700160544",
                            UpdatedDate = new DateTime(2024, 4, 1, 20, 25, 49, 620, DateTimeKind.Local).AddTicks(8484)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
